'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { 
  Sparkles, 
  ChefHat, 
  Plus, 
  X, 
  Clock, 
  Check, 
  Loader2, 
  Flame, 
  Utensils, 
  Copy, 
  CheckCircle2, 
  AlertTriangle,
  ChevronDown,
  ChevronUp,
  ArrowRight
} from 'lucide-react';

const COMMON_INGREDIENTS = [
  'Eggs', 'Chicken', 'Garlic', 'Onion', 'Tomato', 'Spinach', 
  'Cheese', 'Pasta', 'Rice', 'Avocado', 'Potato', 'Mushrooms', 
  'Bell Pepper', 'Lemon', 'Broccoli', 'Ground Beef'
];

export default function AIChefPage() {
  const [ingredients, setIngredients] = useState(['Eggs', 'Tomato', 'Garlic']);
  const [customInput, setCustomInput] = useState('');
  const [mealType, setMealType] = useState('Dinner');
  const [maxTime, setMaxTime] = useState('30');
  const [dietaryPreference, setDietaryPreference] = useState('None');

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [recipes, setRecipes] = useState(null);
  const [copiedId, setCopiedId] = useState(null);
  const [expandedRecipeId, setExpandedRecipeId] = useState(null);

  // Add custom ingredient from input
  const handleAddIngredient = (e) => {
    e?.preventDefault();
    const clean = customInput.trim();
    if (clean && !ingredients.some(i => i.toLowerCase() === clean.toLowerCase())) {
      setIngredients(prev => [...prev, clean]);
      setCustomInput('');
      setError('');
    }
  };

  // Toggle common ingredient pill
  const toggleCommonIngredient = (item) => {
    if (ingredients.some(i => i.toLowerCase() === item.toLowerCase())) {
      setIngredients(ingredients.filter(i => i.toLowerCase() !== item.toLowerCase()));
    } else {
      setIngredients([...ingredients, item]);
      setError('');
    }
  };

  // Remove tag
  const handleRemoveIngredient = (itemToRemove) => {
    setIngredients(ingredients.filter(i => i !== itemToRemove));
  };

  // Clear all
  const handleClearAll = () => {
    setIngredients([]);
  };

  // Call AI Pantry Chef API
  const handleGenerate = async () => {
    if (ingredients.length === 0) {
      setError('Please add at least one ingredient from your kitchen or fridge.');
      return;
    }

    setLoading(true);
    setError('');
    setRecipes(null);

    try {
      const res = await fetch('/api/ai/pantry-chef', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ingredients,
          mealType,
          maxTime: parseInt(maxTime, 10) || null,
          dietaryPreference,
        }),
      });

      const data = await res.json();
      if (res.ok && data.success && Array.isArray(data.data)) {
        setRecipes(data.data);
        if (data.data.length > 0) {
          setExpandedRecipeId(data.data[0].id || 0);
        }
      } else {
        setError(data.message || 'Failed to generate recipes. Please try again.');
      }
    } catch (err) {
      console.error('Pantry Chef Error:', err);
      setError('Failed to reach AI service. Please check your network.');
    } finally {
      setLoading(false);
    }
  };

  // Copy recipe to clipboard
  const handleCopyRecipe = (recipe, index) => {
    const text = `🍽️ ${recipe.recipeName}
${recipe.tagline || ''}

Category: ${recipe.category} | Cuisine: ${recipe.cuisineType} | Prep: ${recipe.preparationTime} mins | Level: ${recipe.difficultyLevel}

🛒 INGREDIENTS:
${recipe.ingredients ? recipe.ingredients.map(i => `• ${i}`).join('\n') : ''}

🍳 INSTRUCTIONS:
${recipe.instructions}

💡 Why It Works: ${recipe.whyItWorks || ''}
(Generated by RecipeHub AI Pantry Chef)`;

    navigator.clipboard.writeText(text);
    setCopiedId(index);
    setTimeout(() => setCopiedId(null), 3000);
  };

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-10">
      {/* Hero Header */}
      <div className="text-center space-y-3 max-w-3xl mx-auto">
        <div className="inline-flex items-center gap-2 bg-gradient-to-r from-amber-500/10 via-orange-500/10 to-brand/10 border border-amber-500/20 px-4 py-1.5 rounded-full text-xs font-bold text-amber-600 dark:text-amber-400">
          <Sparkles size={14} className="animate-pulse text-amber-500" />
          <span>Powered by Google Gemini 3.6 Flash</span>
        </div>
        <h1 className="text-3xl sm:text-5xl font-black text-foreground-custom tracking-tight">
          What&apos;s in your fridge?
        </h1>
        <p className="text-sm sm:text-base text-foreground-custom/70 leading-relaxed">
          Tell our AI Chef what ingredients you have sitting in your pantry or fridge. We&apos;ll invent delicious, custom recipes tailored specifically to your ingredients with zero food waste!
        </p>
      </div>

      {/* Main Pantry Input Box */}
      <div className="bg-card-custom border border-border-custom rounded-3xl p-6 sm:p-8 shadow-sm space-y-6 max-w-4xl mx-auto">
        {/* Ingredient Input */}
        <div className="space-y-3">
          <label className="text-xs font-bold uppercase tracking-wider text-foreground-custom/70 block">
            Add Your Ingredients
          </label>
          <form onSubmit={handleAddIngredient} className="flex gap-2">
            <input
              type="text"
              value={customInput}
              onChange={(e) => setCustomInput(e.target.value)}
              placeholder="Type an ingredient (e.g. leftover chicken, zucchini, soy sauce)..."
              className="flex-1 bg-foreground-custom/5 border border-border-custom rounded-2xl px-4 py-3 text-sm text-foreground-custom focus:outline-none focus:border-brand"
            />
            <button
              type="submit"
              disabled={!customInput.trim()}
              className="bg-brand hover:bg-brand-hover text-white font-semibold px-5 py-3 rounded-2xl text-sm transition-all flex items-center gap-1.5 disabled:opacity-40 cursor-pointer shrink-0"
            >
              <Plus size={16} />
              <span>Add</span>
            </button>
          </form>

          {/* Quick Add Pills */}
          <div className="space-y-1.5 pt-1">
            <span className="text-[11px] font-medium text-foreground-custom/60 block">
              Quick tap to add common items:
            </span>
            <div className="flex flex-wrap gap-1.5">
              {COMMON_INGREDIENTS.map((item) => {
                const isSelected = ingredients.some(i => i.toLowerCase() === item.toLowerCase());
                return (
                  <button
                    key={item}
                    type="button"
                    onClick={() => toggleCommonIngredient(item)}
                    className={`text-xs px-3 py-1 rounded-full border transition-all cursor-pointer flex items-center gap-1 ${
                      isSelected
                        ? 'bg-brand text-white border-brand shadow-sm font-semibold'
                        : 'bg-foreground-custom/5 hover:bg-foreground-custom/10 text-foreground-custom/80 border-border-custom'
                    }`}
                  >
                    {isSelected ? <Check size={12} /> : <Plus size={12} />}
                    <span>{item}</span>
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        {/* Active Selected Ingredients */}
        <div className="space-y-2 pt-2 border-t border-border-custom">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-foreground-custom">
              Your Kitchen Basket ({ingredients.length} items):
            </span>
            {ingredients.length > 0 && (
              <button
                type="button"
                onClick={handleClearAll}
                className="text-xs text-red-500 hover:underline"
              >
                Clear all
              </button>
            )}
          </div>

          {ingredients.length === 0 ? (
            <p className="text-xs text-foreground-custom/50 italic py-2">
              No ingredients selected yet. Type above or tap any quick-add item!
            </p>
          ) : (
            <div className="flex flex-wrap gap-2 pt-1">
              {ingredients.map((item, idx) => (
                <span
                  key={idx}
                  className="inline-flex items-center gap-1.5 bg-brand/10 border border-brand/20 text-brand text-xs font-medium px-3 py-1.5 rounded-full"
                >
                  <span>{item}</span>
                  <button
                    type="button"
                    onClick={() => handleRemoveIngredient(item)}
                    className="hover:text-red-500 transition-colors p-0.5"
                  >
                    <X size={13} />
                  </button>
                </span>
              ))}
            </div>
          )}
        </div>

        {/* Preferences Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-3 border-t border-border-custom">
          <div className="space-y-1">
            <label className="text-xs font-bold text-foreground-custom">Meal Type</label>
            <select
              value={mealType}
              onChange={(e) => setMealType(e.target.value)}
              className="w-full bg-foreground-custom/5 border border-border-custom rounded-xl p-2.5 text-sm text-foreground-custom focus:outline-none focus:border-brand"
            >
              <option value="Any">Any Meal</option>
              <option value="Dinner">Dinner</option>
              <option value="Lunch">Lunch</option>
              <option value="Breakfast">Breakfast</option>
              <option value="Snack">Snack / Appetizer</option>
              <option value="Dessert">Dessert</option>
            </select>
          </div>

          <div className="space-y-1">
            <label className="text-xs font-bold text-foreground-custom">Max Cook Time</label>
            <select
              value={maxTime}
              onChange={(e) => setMaxTime(e.target.value)}
              className="w-full bg-foreground-custom/5 border border-border-custom rounded-xl p-2.5 text-sm text-foreground-custom focus:outline-none focus:border-brand"
            >
              <option value="">Any Time</option>
              <option value="15">Under 15 mins</option>
              <option value="30">Under 30 mins</option>
              <option value="45">Under 45 mins</option>
              <option value="60">Under 60 mins</option>
            </select>
          </div>

          <div className="space-y-1">
            <label className="text-xs font-bold text-foreground-custom">Dietary Needs</label>
            <select
              value={dietaryPreference}
              onChange={(e) => setDietaryPreference(e.target.value)}
              className="w-full bg-foreground-custom/5 border border-border-custom rounded-xl p-2.5 text-sm text-foreground-custom focus:outline-none focus:border-brand"
            >
              <option value="None">None / Flexible</option>
              <option value="Vegetarian">Vegetarian</option>
              <option value="Vegan">Vegan</option>
              <option value="Gluten-Free">Gluten-Free</option>
              <option value="Keto">Keto</option>
              <option value="Low Carb">Low Carb</option>
              <option value="High Protein">High Protein</option>
              <option value="Dairy-Free">Dairy-Free</option>
            </select>
          </div>
        </div>

        {error && (
          <div className="flex items-start space-x-2.5 p-4 rounded-2xl bg-red-500/10 border border-red-500/20 text-red-500 text-sm">
            <AlertTriangle size={18} className="shrink-0 mt-0.5" />
            <span>{error}</span>
          </div>
        )}

        {/* Generate Button */}
        <div>
          <button
            type="button"
            onClick={handleGenerate}
            disabled={loading || ingredients.length === 0}
            className="w-full bg-gradient-to-r from-amber-500 via-orange-500 to-brand hover:opacity-95 text-white font-bold py-4 px-8 rounded-2xl transition-all shadow-lg flex items-center justify-center space-x-2 text-base disabled:opacity-50 cursor-pointer"
          >
            {loading ? (
              <>
                <Loader2 size={20} className="animate-spin" />
                <span>AI Chef is creating recipes from your pantry...</span>
              </>
            ) : (
              <>
                <Sparkles size={20} />
                <span>Find Recipes with My Ingredients ✨</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Generated Recipes List */}
      {recipes && recipes.length > 0 && (
        <div className="space-y-6 max-w-4xl mx-auto pt-4">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-2xl font-bold text-foreground-custom flex items-center gap-2">
                <ChefHat className="text-brand" size={24} />
                <span>Recipes You Can Make Right Now</span>
              </h2>
              <p className="text-xs text-foreground-custom/60">
                Created specifically using your basket of {ingredients.length} items.
              </p>
            </div>
            <span className="text-xs font-semibold bg-brand/10 text-brand px-3 py-1 rounded-full">
              {recipes.length} suggestions
            </span>
          </div>

          <div className="grid grid-cols-1 gap-6">
            {recipes.map((r, idx) => {
              const isExpanded = expandedRecipeId === (r.id || idx);
              return (
                <div
                  key={r.id || idx}
                  className="bg-card-custom border border-border-custom rounded-3xl p-6 sm:p-8 shadow-sm space-y-5 transition-all"
                >
                  {/* Recipe Card Header */}
                  <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3">
                    <div className="space-y-1.5 flex-1">
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="text-xs bg-brand/10 text-brand font-bold px-3 py-1 rounded-full uppercase">
                          {r.category}
                        </span>
                        <span className="text-xs bg-foreground-custom/5 text-foreground-custom/70 font-medium px-3 py-1 rounded-full">
                          {r.cuisineType}
                        </span>
                        <span className="text-xs bg-foreground-custom/5 text-foreground-custom/70 font-medium px-3 py-1 rounded-full capitalize">
                          {r.difficultyLevel}
                        </span>
                      </div>
                      <h3 className="text-xl sm:text-2xl font-black text-foreground-custom tracking-tight">
                        {r.recipeName}
                      </h3>
                      {r.tagline && (
                        <p className="text-xs sm:text-sm text-foreground-custom/70 italic">
                          {r.tagline}
                        </p>
                      )}
                    </div>

                    <div className="flex items-center gap-2 shrink-0 self-start">
                      <div className="flex items-center gap-1.5 text-xs font-semibold text-foreground-custom/70 bg-foreground-custom/5 px-3 py-2 rounded-xl">
                        <Clock size={15} className="text-brand" />
                        <span>{r.preparationTime} mins</span>
                      </div>
                    </div>
                  </div>

                  {/* Why it works pill */}
                  {r.whyItWorks && (
                    <div className="bg-amber-500/10 border border-amber-500/20 rounded-2xl p-4 text-xs text-amber-800 dark:text-amber-200">
                      <strong>Chef&apos;s Note:</strong> {r.whyItWorks}
                    </div>
                  )}

                  {/* Matched Pantry Items Tag Bar */}
                  <div className="space-y-2 pt-2 border-t border-border-custom">
                    <div className="text-xs font-bold text-foreground-custom flex items-center gap-1.5">
                      <CheckCircle2 size={15} className="text-green-500" />
                      <span>Uses from your kitchen:</span>
                    </div>
                    <div className="flex flex-wrap gap-1.5">
                      {r.matchedIngredients?.map((item, mIdx) => (
                        <span
                          key={mIdx}
                          className="text-xs bg-green-500/10 text-green-700 dark:text-green-300 font-medium px-2.5 py-0.5 rounded-full border border-green-500/20"
                        >
                          ✓ {item}
                        </span>
                      ))}
                      {r.additionalPantryItems?.map((staple, sIdx) => (
                        <span
                          key={sIdx}
                          className="text-xs bg-foreground-custom/5 text-foreground-custom/60 px-2 py-0.5 rounded-full"
                        >
                          + {staple}
                        </span>
                      ))}
                    </div>
                  </div>

                  {/* Expand / Collapse Details */}
                  {isExpanded && (
                    <div className="space-y-6 pt-4 border-t border-border-custom">
                      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        {/* Ingredients */}
                        <div className="md:col-span-1 space-y-2">
                          <h4 className="text-xs font-bold uppercase tracking-wider text-foreground-custom flex items-center gap-1.5">
                            <Utensils size={14} className="text-brand" />
                            <span>Ingredients with Measurements</span>
                          </h4>
                          <ul className="space-y-1.5 bg-foreground-custom/5 p-4 rounded-2xl text-xs text-foreground-custom/80">
                            {r.ingredients?.map((ing, iIdx) => (
                              <li key={iIdx} className="flex items-start gap-1.5">
                                <span className="h-1.5 w-1.5 rounded-full bg-brand shrink-0 mt-1.5" />
                                <span>{ing}</span>
                              </li>
                            ))}
                          </ul>
                        </div>

                        {/* Instructions */}
                        <div className="md:col-span-2 space-y-2">
                          <h4 className="text-xs font-bold uppercase tracking-wider text-foreground-custom">
                            Cooking Steps
                          </h4>
                          <div className="bg-foreground-custom/5 p-4 sm:p-5 rounded-2xl text-xs sm:text-sm text-foreground-custom/85 whitespace-pre-wrap leading-relaxed">
                            {r.instructions}
                          </div>
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Actions Bar */}
                  <div className="flex flex-wrap items-center justify-between gap-3 pt-3 border-t border-border-custom">
                    <button
                      type="button"
                      onClick={() => setExpandedRecipeId(isExpanded ? null : (r.id || idx))}
                      className="text-xs font-bold text-brand hover:underline flex items-center gap-1 cursor-pointer"
                    >
                      <span>{isExpanded ? 'Hide instructions' : 'View full recipe instructions'}</span>
                      {isExpanded ? <ChevronUp size={15} /> : <ChevronDown size={15} />}
                    </button>

                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={() => handleCopyRecipe(r, idx)}
                        className="flex items-center gap-1.5 text-xs font-semibold text-foreground-custom/70 border border-border-custom hover:bg-foreground-custom/5 px-4 py-2 rounded-xl transition-all cursor-pointer"
                      >
                        {copiedId === idx ? (
                          <>
                            <Check size={14} className="text-green-500" />
                            <span className="text-green-500">Copied!</span>
                          </>
                        ) : (
                          <>
                            <Copy size={14} />
                            <span>Copy Recipe</span>
                          </>
                        )}
                      </button>

                      <Link
                        href="/dashboard/add-recipe"
                        className="flex items-center gap-1 text-xs font-bold bg-brand hover:bg-brand-hover text-white px-4 py-2 rounded-xl transition-all shadow-sm"
                      >
                        <span>Publish to Community</span>
                        <ArrowRight size={13} />
                      </Link>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
